version: "3"
services:
  web:
    build: ./api
    tty: true
    stdin_open: true
    ports:
      - 8083:8083
    volumes:
      - ./api:/app
      - bundle:/usr/local/bundle
    command: bundle exec rails s -p 8083 -b '0.0.0.0'
    depends_on:
      - db
  db: 
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  bundle:
  mysql_data:
