openapi: 3.0.0
info:
  title: Nan Log
  version: 1.0.0
servers:
  - url: http://localhost:8083
    description: Development Server
paths:
  /api/users/{id}:
    get:
      description: ユーザ情報取得
      operationId: getUser
      parameters:
        - in: path
          name: id
          schema:
            type: integer
            format: int32
          required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: number
          example: 1
          readOnly: true
        name:
          type: string
          example: 山田太郎
      required:
        - id
        - name
